apiVersion: v1
kind: Secret
metadata:
  name: grafana-oauth-proxy-secret
  namespace: grafana
data:
  session_secret: "nQnjFo0dV+TAWHCWzXdMi3rp/PR8SpS44LhnDc8PHyxNzPYNF+TPtclpfzwitULQIzSvmB256Ch80CGRO8QltYN15Bjrpr6GYtu0M+baFuVGIgbmdCkVzaFe1lxUIIdtweY36Kb1aDraBrIJtwEPTGUSLOQwtLgaimcilr8z9+E="