apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-storage
  namespace: grafana
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: topolvm.io
    volume.kubernetes.io/selected-node: sno.stwihtburh.com
    volume.kubernetes.io/storage-provisioner: topolvm.io
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
    limits:
      storage: 100Gi
  storageClassName: lvms-vg1